#  Copyright (c) 2025 AshokShau
#  Licensed under the GNU AGPL v3.0: https://www.gnu.org/licenses/agpl-3.0.html
#  Part of the TgMusicBot project. All rights reserved where applicable.

#  NOTE: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
#  Configure environment variables using a `.env` file instead.

import os
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from src.logger import LOGGER

load_dotenv()


def get_env_int(name: str, default: Optional[int] = None) -> Optional[int]:
    """
    Retrieve an environment variable and convert it to an integer.

    Args:
        name (str): Environment variable name.
        default (Optional[int]): Fallback value if parsing fails.

    Returns:
        Optional[int]: Parsed integer or the default value.
    """
    value = os.getenv(name)
    try:
        return int(value)
    except (TypeError, ValueError):
        LOGGER.warning("Invalid value for %s: %s (default: %s)", name, value, default)
        return default


def get_env_bool(name: str, default: bool = False) -> bool:
    """
    Retrieve an environment variable and interpret it as a boolean.

    Args:
        name (str): Environment variable name.
        default (bool): Default boolean value.

    Returns:
        bool: Parsed boolean value.
    """
    return os.getenv(name, str(default)).lower() == "true"


def get_session_strings(prefix: str = "STRING", count: int = 10) -> list[str]:
    """
    Retrieve multiple session strings from the environment.

    Args:
        prefix (str): Prefix of the environment variable.
        count (int): Number of session keys to check.

    Returns:
        list[str]: A list of valid session strings.
    """
    return [s.strip() for i in range(1, count + 1) if (s := os.getenv(f"{prefix}{i}"))]


def process_cookie_urls(value: Optional[str]) -> list[str]:
    """
    Parse space- or comma-separated URLs into a list.

    Args:
        value (Optional[str]): Raw COOKIES_URL env value.

    Returns:
        list[str]: List of cleaned URL strings.
    """
    if not value:
        return []
    return [url.strip() for url in value.replace(",", " ").split() if url.strip()]


# Core Bot Configuration
API_ID: Optional[int] = get_env_int("API_ID")
API_HASH: Optional[str] = os.getenv("API_HASH")
TOKEN: Optional[str] = os.getenv("TOKEN")

SESSION_STRINGS: list[str] = get_session_strings()
MONGO_URI: Optional[str] = os.getenv("MONGO_URI")
API_URL: str = os.getenv("API_URL", "https://tgmusic.fallenapi.fun")
API_KEY: Optional[str] = os.getenv("API_KEY")

# Owner and Logger
OWNER_ID: int = get_env_int("OWNER_ID", 5938660179)
LOGGER_ID: int = get_env_int("LOGGER_ID", -1002166934878)

# Optional Settings
PROXY: Optional[str] = os.getenv("PROXY")
DEFAULT_SERVICE: str = os.getenv("DEFAULT_SERVICE", "youtube").lower()
MIN_MEMBER_COUNT: int = get_env_int("MIN_MEMBER_COUNT", 50)

DOWNLOADS_DIR: Path = Path(os.getenv("DOWNLOADS_DIR", "database/music"))

SUPPORT_GROUP: str = os.getenv("SUPPORT_GROUP", "https://t.me/GuardxSupport")
SUPPORT_CHANNEL: str = os.getenv("SUPPORT_CHANNEL", "https://t.me/FallenProjects")

IGNORE_BACKGROUND_UPDATES: bool = get_env_bool("IGNORE_BACKGROUND_UPDATES", True)
AUTO_LEAVE: bool = get_env_bool("AUTO_LEAVE", True)

# Cookies
COOKIES_URL: list[str] = process_cookie_urls(os.getenv("COOKIES_URL"))

# Developers
devs_env: Optional[str] = os.getenv("DEVS")
DEVS: list[int] = list(map(int, devs_env.split())) if devs_env else []
if OWNER_ID and OWNER_ID not in DEVS:
    DEVS.append(OWNER_ID)
