#  Copyright (c) 2025 AshokShau
#  Licensed under the GNU AGPL v3.0: https://www.gnu.org/licenses/agpl-3.0.html
#  Part of the TgMusicBot project. All rights reserved where applicable.

#  NOTE: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
#  Configure environment variables using the .env file instead

from os import getenv
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

API_ID = int(getenv("API_ID", None))
API_HASH = getenv("API_HASH", None)
TOKEN = getenv("TOKEN", None)
STRING = getenv("STRING", None)
STRING2 = getenv("STRING2", None)
STRING3 = getenv("STRING3", None)
STRING4 = getenv("STRING4", None)
STRING5 = getenv("STRING5", None)
STRING6 = getenv("STRING6", None)
STRING7 = getenv("STRING7", None)
STRING8 = getenv("STRING8", None)
STRING9 = getenv("STRING9", None)
STRING10 = getenv("STRING10", None)

SESSION_STRINGS = [
    STRING,
    STRING2,
    STRING3,
    STRING4,
    STRING5,
    STRING6,
    STRING7,
    STRING8,
    STRING9,
    STRING10,
]
OWNER_ID = int(getenv("OWNER_ID", 5938660179))
LOGGER_ID = int(getenv("LOGGER_ID", 0))
MONGO_URI = getenv("MONGO_URI", None)
API_URL = getenv("API_URL", None)
API_KEY = getenv("API_KEY", None)
PROXY_URL = getenv("PROXY_URL", None)
DEFAULT_SERVICE = getenv("DEFAULT_SERVICE", "youtube").lower()
DOWNLOADS_DIR = getenv("DOWNLOADS_DIR", "database/music")
SUPPORT_GROUP = getenv("SUPPORT_GROUP", "https://t.me/GuardxSupport")
SUPPORT_CHANNEL = getenv("SUPPORT_CHANNEL", "https://t.me/FallenProjects")
IGNORE_BACKGROUND_UPDATES = (
    getenv("IGNORE_BACKGROUND_UPDATES", "True").lower() == "true"
)


def process_cookie_urls(env_value: Optional[str]) -> list[str]:
    """https://github.com/AshokShau/TgMusicBot/blob/master/cookies/README.md"""
    if not env_value:
        return []
    urls = []
    for part in env_value.split(","):
        urls.extend(part.split())

    return [url.strip() for url in urls if url.strip()]


COOKIES_URL: list[str] = process_cookie_urls(getenv("COOKIES_URL", ""))
